
def get_property_setters():
    property_setters = [
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "desk_theme",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "name": "User-desk_theme-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "banner_image",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:54.081802",
            "module": "Akwad Frappe Fixes",
            "name": "User-banner_image-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "change_password",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:40:42.813633",
            "module": "Akwad Frappe Fixes",
            "name": "User-change_password-collapsible",
            "property": "collapsible",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "document_follow_notify",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:41:14.412836",
            "module": "Akwad Frappe Fixes",
            "name": "User-document_follow_notify-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "thread_notify",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:41:43.682428",
            "module": "Akwad Frappe Fixes",
            "name": "User-thread_notify-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "send_me_a_copy",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:41:51.503754",
            "module": "Akwad Frappe Fixes",
            "name": "User-send_me_a_copy-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "allowed_in_mentions",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:42:09.162876",
            "module": "Akwad Frappe Fixes",
            "name": "User-allowed_in_mentions-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "simultaneous_sessions",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:42:36.267119",
            "module": "Akwad Frappe Fixes",
            "name": "User-simultaneous_sessions-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "social_logins",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:42:46.369943",
            "module": "Akwad Frappe Fixes",
            "name": "User-social_logins-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "sb3",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:43:49.675191",
            "module": "Akwad Frappe Fixes",
            "name": "User-security_settings-permlevel",
            "property": "collapsible",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "connections_tab",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:44:44.426648",
            "module": "Akwad Frappe Fixes",
            "name": "User-connections_tab-hidden",
            "property": "hidden",
            "property_type": "Check",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "role_profile_name",
            "is_system_generated": 0,
            "modified": "2024-02-29 14:19:27.730382",
            "module": "Akwad Frappe Fixes",
            "name": "User-role_profile_name-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "roles_html",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:49:39.297259",
            "module": "Akwad Frappe Fixes",
            "name": "User-roles_html-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "module_profile",
            "is_system_generated": 0,
            "modified": "2024-02-29 14:12:26.870974",
            "module": "Akwad Frappe Fixes",
            "name": "User-module_profile-permlevel",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-01-03 16:59:52.412395",
            "module": "Akwad Frappe Fixes",
            "name": "User-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "Notification Settings",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocType",
            "field_name": None,
            "is_system_generated": 0,
            "modified": "2024-04-17 23:50:41.780762",
            "module": "Akwad Frappe Fixes",
            "name": "Notification Settings-main-track_changes",
            "property": "track_changes",
            "property_type": "Check",
            "row_name": None,
            "value": "0"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "search_bar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-search_bar-permlevel"

        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "notifications",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-notifications-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "list_sidebar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-list_sidebar-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "dashboard",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-dashboard-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "timeline",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-timeline-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "form_sidebar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-form_sidebar-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "view_switcher",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-view_switcher-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "bulk_actions",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-bulk_actions-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "search_bar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-search_bar-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "notifications",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-notifications-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "list_sidebar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-list_sidebar-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "dashboard",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-dashboard-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "timeline",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-timeline-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "form_sidebar",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-form_sidebar-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "view_switcher",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-view_switcher-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "bulk_actions",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "default",
            "property_type": "Text",
            "row_name": None,
            "value": "0",
            "name": "User-bulk_actions-default"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "default_workspace",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-default_workspace-permlevel"
        },
        {
            "default_value": None,
            "doc_type": "User",
            "docstatus": 0,
            "doctype": "Property Setter",
            "doctype_or_field": "DocField",
            "field_name": "default_app",
            "is_system_generated": 0,
            "modified": "2024-02-29 13:39:42.558789",
            "module": "Akwad Frappe Fixes",
            "property": "permlevel",
            "property_type": "Int",
            "row_name": None,
            "value": "1",
            "name": "User-default_app-permlevel"
        }
    ]

    return property_setters
